<<<<<<< HEAD
import Head from 'next/head'
import {affichageLabs} from '@components/Header/lab'
=======
import Head from 'next/head';

>>>>>>> 1b5845abfc7236e9e160445ea52a5df8e8bf05e9
export default function Home() {
  return (
    <>
      <Head>
        <title>Garage ISEP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Garage-logo.svg" />
      </Head>
      <h1 className="text-4xl font-bold">Garage ISEP Website </h1>
      <affichageLabs/>
    </>
  );
}
